#!/bin/bash

SERVER_IP="" # change me
SERVER_PORT="" # change me
SECRET_KEY="" # change me


# Define colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}Starting Paqet Client Setup...${NC}"

# ==============================================================================
# 1. Detect OS and Architecture (First, to check for existing binary)
# ==============================================================================
echo -e "${YELLOW}[Step 1] Detecting Operating System...${NC}"

OS_RAW="$(uname -s)"
ARCH_RAW="$(uname -m)"

OS_TYPE=""
FILE_EXT=""
ARCH_TYPE=""
BINARY_NAME="paqet"

case "${OS_RAW}" in
    Linux*)
        OS_TYPE="linux"
        FILE_EXT=".tar.gz"
        ;;
    Darwin*)
        OS_TYPE="darwin"
        FILE_EXT=".tar.gz"
        ;;
    CYGWIN*|MINGW*|MSYS*)
        OS_TYPE="windows"
        FILE_EXT=".zip"
        BINARY_NAME="paqet.exe"
        ;;
    *)
        OS_TYPE="UNKNOWN"
        ;;
esac

case "${ARCH_RAW}" in
    x86_64)  ARCH_TYPE="amd64" ;;
    aarch64) ARCH_TYPE="arm64" ;;
    armv7l)  ARCH_TYPE="arm32" ;;
    *)       ARCH_TYPE="unknown" ;;
esac

if [[ "$OS_TYPE" == "UNKNOWN" || "$ARCH_TYPE" == "unknown" ]]; then
    echo -e "${RED}[Error] Could not detect supported OS or Architecture.${NC}"
    exit 1
fi

echo -e "${GREEN}[Info] Detected: $OS_TYPE / $ARCH_TYPE${NC}"

# ==============================================================================
# 2. Check for Existing Binary & User Inputs
# ==============================================================================
echo -e "${YELLOW}[Step 2] Configuration Setup${NC}"

SKIP_DOWNLOAD=false

if [ -f "$BINARY_NAME" ]; then
    echo -e "${GREEN}[Info] Found existing '$BINARY_NAME'. Skipping binary download.${NC}"
    SKIP_DOWNLOAD=true
fi

# Only ask for version if we need to download
if [ "$SKIP_DOWNLOAD" = false ]; then
    read -p "Enter Paqet Version (e.g., v1.0.0-alpha.14): " PAQET_VERSION
    if [[ -z "$PAQET_VERSION" ]]; then
        echo -e "${RED}[Error] Version is required for download.${NC}"
        exit 1
    fi
fi

echo -e "$SERVER_IP"
echo "Please enter the connection details generated by your server script."
if [[ -z "$SERVER_IP" ]]; then
  read -p "Enter Server IP Address: " SERVER_IP
fi

if [[ -z "$SERVER_PORT" ]]; then
  read -p "Enter Server Port: " SERVER_PORT
fi

if [[ -z "$SECRET_KEY" ]]; then
  read -p "Enter Secret Key: " SECRET_KEY
fi


if [[ -z "$SERVER_IP" || -z "$SERVER_PORT" || -z "$SECRET_KEY" ]]; then
    echo -e "${RED}[Error] Connection fields are required. Exiting.${NC}"
    exit 1
fi

# ==============================================================================
# 3. Download Paqet Release (Skipped if file exists)
# ==============================================================================
if [ "$SKIP_DOWNLOAD" = false ]; then
    echo -e "${YELLOW}[Step 3] Downloading Paqet ($PAQET_VERSION) for $OS_TYPE...${NC}"

    REPO="hanselime/paqet"
    DOWNLOAD_URL=$(curl -s "https://api.github.com/repos/$REPO/releases/tags/$PAQET_VERSION" | grep "browser_download_url" | grep -i "$OS_TYPE" | grep -i "$ARCH_TYPE" | cut -d '"' -f 4 | head -n 1)

    if [ -z "$DOWNLOAD_URL" ]; then
        echo -e "${RED}[Error] Release not found for version '$PAQET_VERSION'. Check version number.${NC}"
        exit 1
    else
        echo -e "${GREEN}[Info] Downloading: $DOWNLOAD_URL${NC}"
        FILENAME="paqet_download$FILE_EXT"
        wget -q --show-progress -O "$FILENAME" "$DOWNLOAD_URL"

        echo -e "${YELLOW}[Info] Extracting...${NC}"
        if [[ "$FILE_EXT" == ".zip" ]]; then
            if ! command -v unzip &> /dev/null; then
                echo -e "${RED}[Error] 'unzip' command not found. Install unzip.${NC}"
                exit 1
            fi
            unzip -o "$FILENAME" -d . > /dev/null
        else
            tar -xzf "$FILENAME"
        fi
        rm "$FILENAME"

        # Normalize binary name
        if [[ "$OS_TYPE" == "windows" ]]; then
            BIN_NAME=$(find . -maxdepth 1 -name "paqet_windows*.exe" | head -n 1)
            if [ -f "$BIN_NAME" ]; then mv "$BIN_NAME" paqet.exe; fi
        else
            BIN_NAME=$(find . -maxdepth 1 -name "paqet_${OS_TYPE}*" | head -n 1)
            if [ -f "$BIN_NAME" ]; then mv "$BIN_NAME" paqet; chmod +x paqet; fi
        fi
        echo -e "${GREEN}[Success] Paqet installed.${NC}"
    fi
else
    echo -e "${YELLOW}[Step 3] Binary download skipped.${NC}"
fi

# ==============================================================================
# 4. Universal Linux Library Fix (Manjaro/Fedora/Arch)
# ==============================================================================
if [[ "$OS_TYPE" == "linux" ]]; then
    echo -e "${YELLOW}[Step 4] Checking Shared Libraries (libpcap)...${NC}"

    LIB_ERROR=$(./paqet --help 2>&1 | grep "libpcap.so.0.8")

    if [[ -n "$LIB_ERROR" ]]; then
        echo -e "${RED}[Alert] Missing 'libpcap.so.0.8'.${NC}"
        echo -e "${YELLOW}[Fix] Searching for compatible system library...${NC}"

        FOUND_LIB=$(find /usr/lib /usr/lib64 /lib /usr/local/lib -name "libpcap.so*" -print -quit 2>/dev/null)

        if [ -n "$FOUND_LIB" ]; then
            LIB_DIR=$(dirname "$FOUND_LIB")
            echo -e "${GREEN}[Info] Found library: $FOUND_LIB${NC}"
            echo -e "${YELLOW}[Fix] Creating compatibility symlink... (Requires Sudo)${NC}"
            sudo ln -s "$FOUND_LIB" "$LIB_DIR/libpcap.so.0.8"
            echo -e "${GREEN}[Success] Symlink created.${NC}"
        else
            echo -e "${RED}[Error] Could not find any libpcap installed. Please install 'libpcap' via your package manager.${NC}"
            exit 1
        fi
    else
        echo -e "${GREEN}[Check] Library dependencies look good.${NC}"
    fi
fi

# ==============================================================================
# 5. Windows Specific: Npcap
# ==============================================================================
if [[ "$OS_TYPE" == "windows" ]]; then
    if [ ! -f "npcap-installer.exe" ]; then
        echo -e "${YELLOW}[Step 5] Downloading Npcap (Required for Windows)...${NC}"
        wget -q --show-progress -O "npcap-installer.exe" "https://npcap.com/dist/npcap-1.87.exe"
        echo -e "${RED}IMPORTANT: If Npcap is not installed, run 'npcap-installer.exe' manually.${NC}"
    fi
fi

# ==============================================================================
# 6. Network Intelligence (Detect IPs/MACs)
# ==============================================================================
echo -e "${YELLOW}[Step 6] Detecting Local Network Configuration...${NC}"

LOCAL_IFACE=""
LOCAL_IP4=""
GW_MAC=""
LOCAL_IP6=""
GW_MAC6=""

if [[ "$OS_TYPE" == "linux" ]]; then
    LOCAL_IFACE=$(ip route | grep default | awk '{print $5}' | head -n1)
    LOCAL_IP4=$(ip -4 addr show $LOCAL_IFACE | grep -oP "(?<=inet ).*(?=/)" | head -n1)

    GW_IP=$(ip route | grep default | awk '{print $3}' | head -n1)
    ping -c 1 -W 1 $GW_IP > /dev/null 2>&1
    GW_MAC=$(ip neigh show $GW_IP | awk '{print $5}' | head -n1)

    LOCAL_IP6=$(ip -6 addr show $LOCAL_IFACE scope global | grep -oP "(?<=inet6 ).*(?=/)" | head -n1)
    if [ -n "$LOCAL_IP6" ]; then
        GW_IP6=$(ip -6 route | grep default | awk '{print $3}' | head -n1)
        GW_MAC6=$(ip -6 neigh show $GW_IP6 | awk '{print $5}' | head -n1)
    fi

elif [[ "$OS_TYPE" == "windows" ]]; then
    echo -e "${YELLOW}[Info] Probing Windows Network...${NC}"
    LOCAL_IFACE=$(powershell.exe -Command "Get-NetRoute -DestinationPrefix '0.0.0.0/0' | Select-Object -ExpandProperty InterfaceAlias -First 1" | tr -d '\r')
    LOCAL_IP4=$(powershell.exe -Command "Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias '$LOCAL_IFACE' | Select-Object -ExpandProperty IPAddress" | tr -d '\r')
    GW_IP=$(powershell.exe -Command "Get-NetRoute -DestinationPrefix '0.0.0.0/0' | Select-Object -ExpandProperty NextHop" | tr -d '\r')
    GW_MAC=$(powershell.exe -Command "Get-NetNeighbor -IPAddress '$GW_IP' | Select-Object -ExpandProperty LinkLayerAddress" | tr -d '\r')
    GW_MAC=$(echo $GW_MAC | sed 's/-/:/g' | tr '[:upper:]' '[:lower:]')
    LOCAL_IP6=$(powershell.exe -Command "Get-NetIPAddress -AddressFamily IPv6 -InterfaceAlias '$LOCAL_IFACE' -AddressState Preferred | Select-Object -ExpandProperty IPAddress -First 1" | tr -d '\r')
fi

# Fallback values
if [ -z "$GW_MAC" ]; then GW_MAC="00:00:00:00:00:00"; fi
if [ -z "$LOCAL_IFACE" ]; then LOCAL_IFACE="eth0"; fi
if [ -z "$LOCAL_IP4" ]; then LOCAL_IP4="127.0.0.1"; fi

echo -e "${GREEN}[Info] Interface : $LOCAL_IFACE${NC}"
echo -e "${GREEN}[Info] Local IP  : $LOCAL_IP4${NC}"
echo -e "${GREEN}[Info] Gateway MAC: $GW_MAC${NC}"

# ==============================================================================
# 7. Configure client.yaml
# ==============================================================================
echo -e "${YELLOW}[Step 7] configuring client.yaml...${NC}"

if [ ! -f "client.yaml" ]; then
    echo -e "${YELLOW}[Info] client.yaml not found. Downloading template...${NC}"
    wget -q -O client.yaml https://raw.githubusercontent.com/hanselime/paqet/master/example/client.yaml.example
    if [ ! -f "client.yaml" ]; then
        echo -e "${RED}[Error] Failed to download client.yaml.example.${NC}"
        exit 1
    fi
else
    echo -e "${GREEN}[Info] client.yaml exists. Rewriting values...${NC}"
fi

echo -e "${YELLOW}[Config] Applying configuration...${NC}"

# Regex substitutions based on comments in the example file.
# This preserves the comments so the script can be run again.

# 1. Update Network Interface
# Matches line starting with whitespace, 'interface:', anything, then '# CHANGE ME: Network interface'
sed -i "s|^[[:space:]]*interface:.*# CHANGE ME: Network interface.*|  interface: \"$LOCAL_IFACE\"                          # CHANGE ME: Network interface (en0, eth0, wlan0, etc.)|g" client.yaml

# 2. Update IPv4 Address
# Matches '# CHANGE ME: Local IP'
sed -i "s|^[[:space:]]*addr:.*# CHANGE ME: Local IP.*|    addr: \"$LOCAL_IP4:0\"                 # CHANGE ME: Local IP (use port 0 for random port)|g" client.yaml

# 3. Update IPv4 Router MAC
# Matches '# CHANGE ME: Gateway/router MAC address' (excluding IPv6 one which has "for IPv6" at end)
sed -i "s|^[[:space:]]*router_mac:.*# CHANGE ME: Gateway/router MAC address$|    router_mac: \"$GW_MAC\"         # CHANGE ME: Gateway/router MAC address|g" client.yaml

# 4. Update IPv6 (Only if detected, otherwise leave as placeholder)
if [ -n "$LOCAL_IP6" ]; then
    # Address
    sed -i "s|^[[:space:]]*addr:.*# CHANGE ME: Local IPv6.*|    addr: \"[$LOCAL_IP6]:0\"                 # CHANGE ME: Local IPv6 address and port (optional)|g" client.yaml

    if [ -n "$GW_MAC6" ]; then
        # Gateway
        sed -i "s|^[[:space:]]*router_mac:.*# CHANGE ME: Gateway/router MAC address for IPv6.*|    router_mac: \"$GW_MAC6\"         # CHANGE ME: Gateway/router MAC address for IPv6|g" client.yaml
    fi
fi

# 5. Update Server Address
# Matches '# CHANGE ME: paqet server address'
sed -i "s|^[[:space:]]*addr:.*# CHANGE ME: paqet server address.*|  addr: \"$SERVER_IP:$SERVER_PORT\"  # CHANGE ME: paqet server address and port|g" client.yaml

# 6. Update Secret Key
# Matches '# CHANGE ME: Secret key'
sed -i "s|^[[:space:]]*key:.*# CHANGE ME: Secret key.*|    key: \"$SECRET_KEY\"       # CHANGE ME: Secret key (must match server)|g" client.yaml

echo -e "${GREEN}[Success] client.yaml configured.${NC}"

# ==============================================================================
# 8. Start Paqet
# ==============================================================================
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}      Starting Paqet Client...          ${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "${YELLOW}Your SOCKS5 Proxy will be: 127.0.0.1:1080${NC}"

if [[ "$OS_TYPE" == "windows" ]]; then
    echo -e "${YELLOW}Running ./paqet.exe ...${NC}"
    ./paqet.exe run -c client.yaml
else
    echo -e "${YELLOW}Running sudo ./paqet ... (Please enter password if asked)${NC}"
    sudo ./paqet run -c client.yaml
fi